### PR TITLE
c_defines improvement

### PR DESCRIPTION
**Pull request by fafryd1125**
Ping to @aaronp24

I'm not sure if t_tls can be this way
`t_tls = cc.compiles('__thread int foo __attribute__((tls_model("initial-exec")));', name : 'TLS detection')`
Thank you for any comment.

BTW Are there any plans to add meson build to [NVIDIA/libglvnd](https://github.com/NVIDIA/libglvnd)?

### CODE REVIEW

**Comment by aaronp24** [comment]
Thanks! I don't really know why you'd want to disable egl, glx, or gles but it can't hurt to have that option. I merged the first four changes and the last one. Would you mind rebasing and squashing the tls fixes?

As for merging this with upstream, that's up to @kbrenneman. When I asked him about it earlier, he said he didn't want to merge it until it works in Ubuntu 16.04. But the latest meson in xenial-backports is 0.40, and this branch requires 0.41 or higher. If we're going to maintain both build systems, we'll want to deduplicate src/generate/gen_libOpenGL_exports.py vs src/generate/gen_libOpenGL_exports_old.py first.

**Comment by fafryd1125** [comment]
> Would you mind rebasing and squashing the tls fixes?

Done (I hope) :)

> Thanks! I don't really know why you'd want to disable egl, glx, or gles but it can't hurt to have that option.

`./configure` has these options

**Comment by fafryd1125** [comment]
Please merge only ba90160.

**Comment by kbrenneman** [comment]
If you have a working cross-compiler, then there shouldn't be any reason to disable assembly code. You don't have to be able to run the resulting binaries just to compile them.

**Comment by fafryd1125** [comment]
You're  right!
```
Version: 0.44.0
Source dir: /home/pasazer/project/meson/libglvnd-github
Build dir: /home/pasazer/project/meson/build
Build type: native build
Project name: libglvnd
Native C compiler: gcc -m32 (gcc 7.3.0)
Build machine cpu family: x86
Build machine cpu: i686
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency glproto found: YES 1.4.17
Native dependency x11 found: YES 1.6.5
Native dependency xext found: YES 1.3.3
Library dl found: YES
Library m found: YES
Checking if "TLS detection" compiles: YES
Program gen_gldispatch_mapi.py found: YES (/home/pasazer/project/meson/libglvnd-github/src/generate/gen_gldispatch_mapi.py)
Program gen_libgl_glxstubs.py found: YES (/home/pasazer/project/meson/libglvnd-github/src/generate/gen_libgl_glxstubs.py)
Program gen_libOpenGL_exports.py found: YES (/home/pasazer/project/meson/libglvnd-github/src/generate/gen_libOpenGL_exports.py)
Program gen_egl_dispatch.py found: YES (/home/pasazer/project/meson/libglvnd-github/src/generate/gen_egl_dispatch.py)
Build targets in project: 49
Found ninja-1.8.2 at /usr/bin/ninja
```
```
[0/1] Running all tests.
 1/20 gldispatch_static                       OK       0.01 s
 2/20 gldispatch_generated                    OK       0.01 s
 3/20 gldispatch_patched                      OK       0.01 s
 4/20 glxcreatecontext                        OK       0.00 s
 5/20 glxmcbasic                              OK       0.01 s
 6/20 glxmcloop                               OK       0.01 s
 7/20 glxmcthreads                            OK       0.25 s
 8/20 glxmclate                               OK       0.00 s
 9/20 glxmcoldlink                            OK       0.01 s
10/20 glxgetprocaddress                       OK       0.00 s
11/20 glxgetprocaddress_genentry              OK       0.00 s
12/20 glxgetclientstr                         OK       0.00 s
13/20 glxqueryversion                         OK       0.00 s
14/20 patchentrypoints                        OK       0.01 s
15/20 egldisplay                              OK       0.01 s
16/20 egldevice                               OK       0.01 s
17/20 eglgetprocaddress                       OK       0.00 s
18/20 eglmakecurrent                          OK       0.00 s
19/20 eglerror                                OK       0.00 s
20/20 egldebug                                OK       0.00 s

OK:        20
FAIL:       0
SKIP:       0
TIMEOUT:    0

Full log written to /home/pasazer/project/meson/build/meson-logs/testlog.txt

```

Unfortunately, clang probably needs cross_file.txt
http://mesonbuild.com/Cross-compilation.html

**Comment by fafryd1125** [comment]
Should it be like that? (libglvnd-test-asm)
https://gist.github.com/fafryd1125/24d1120dbf8e0ce902f638198b9ab6d3

update:
To be clear, test suite fail only when asm is disabled

**Comment by fafryd1125** [comment]
> Would you mind rebasing and squashing the tls fixes?

@aaronp24 I'm sorry, it can be like this?
https://github.com/fafryd1125/libglvnd/commit/9565e0dc89d9bae84c4abcb3918a6381b0895d9a

**Comment by kbrenneman** [comment]
A bunch of the unit tests will fail when asm is disabled, because it can't generate new dispatch stubs at runtime.

By the same token, though, there are applications out there that will break without those generated stubs.

**Comment by fafryd1125** [comment]
@aaronp24 Please see https://github.com/aaronp24/libglvnd/pull/3. 
Thank you for the review!

**Pull request closed without merging**
